In [1]:
# Se cargan librerías

import pandas as pd

In [3]:
# Se carga archivo csv listings

listingsdf = pd.read_csv('listings.csv')
listingsdf.head()

C:\Users\German\AppData\Local\Temp\ipykernel_16260\1011376186.py:3: DtypeWarning: Columns (61,62,95) have mixed types. Specify dtype option on import or set low_memory=False.
  listingsdf = pd.read_csv('listings.csv')

,id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,11508,https://www.airbnb.com/rooms/11508,20200426042522,2020-04-26,Amazing Luxurious Apt-Palermo Soho,NaN,LUXURIOUS NEW APT: 1 BDRM- POOL/ GYM/ SPA/ 24-...,LUXURIOUS NEW APT: 1 BDRM- POOL/ GYM/ SPA/ 24-...,none,AREA: PALERMO SOHO Minutes walking distance fr...,...,f,f,strict_14_with_grace_period,f,f,1,1,0,0,0.27
1,12463,https://www.airbnb.com/rooms/12463,20200426042522,2020-04-26,Room in Recoleta - awesome location,My apartment is centrally located in Recoleta ...,This is a very comfortable pull-out sofa in th...,My apartment is centrally located in Recoleta ...,none,It's near the school of medicine so the street...,...,f,f,moderate,f,f,1,0,1,0,0.16
2,13095,https://www.airbnb.com/rooms/13095,20200426042522,2020-04-26,Standard Room at Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Standard room : Palermo Viejo Bed & Breakfast ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,0.06
3,13096,https://www.airbnb.com/rooms/13096,20200426042522,2020-04-26,Standard Room in Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Palermo Viejo Bed & Breakfast is located in a ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,NaN
4,13097,https://www.airbnb.com/rooms/13097,20200426042522,2020-04-26,Standard Room at Palermo Viejo B&B,Palermo Viejo B&B is a typical home in one of ...,Palermo Viejo Bed & Breakfast is located in a ...,Palermo Viejo B&B is a typical home in one of ...,none,NaN,...,f,f,strict_14_with_grace_period,f,f,7,0,7,0,1.89

In [4]:
# Se le cambia el nombre a la columna id por 'listing_id' para poder relacionarla con las otras tablas

listingsdf = listingsdf.rename(columns={"id": "listing_id"})

In [5]:
# Se conoce el comportamiento del DataFrame

listingsdf.shape

(23729, 106)

In [6]:
listingsdf.columns

Index(['listing_id', 'listing_url', 'scrape_id', 'last_scraped', 'name',
       'summary', 'space', 'description', 'experiences_offered',
       'neighborhood_overview',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=106)

In [62]:
listingsdf['cancellation_policy']

0        strict_14_with_grace_period
1                           moderate
2        strict_14_with_grace_period
3        strict_14_with_grace_period
4        strict_14_with_grace_period
                    ...
23724                       flexible
23725                       flexible
23726                       flexible
23727                       flexible
23728                       flexible
Name: cancellation_policy, Length: 23729, dtype: object

In [7]:
# Define the list of specific listing IDs
listing_ids = [32463719, 37961786, 1323164, 308320, 867441, 1095098, 1757580, 1922407, 2092376, 2175874]

# Filter rows with listing_id in the specified list
specific_listing_rows = listingsdf[listingsdf['listing_id'].isin(listing_ids)]

# Print the filtered DataFrame
specific_listing_rows

,listing_id,listing_url,scrape_id,last_scraped,name,summary,space,description,experiences_offered,neighborhood_overview,...,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
283,308320,https://www.airbnb.com/rooms/308320,20200426042522,2020-04-27,"SUITE, QUEEN BED, CLOSET AND PRIVATE BATHROOM",This private room has a Queen bed and a great ...,Welcome to Mi Casa en BA: Mi Casa en BA is a t...,This private room has a Queen bed and a great ...,none,Neighbourhood Highlights: Among the architectu...,...,f,f,strict_14_with_grace_period,t,t,7,1,5,1,0.21
674,867441,https://www.airbnb.com/rooms/867441,20200426042522,2020-04-27,BEAUTIFUL CENTRAL ROOM,Rooms to rent in the emblematic district of Al...,Rent beautiful rooms in the picturesque distri...,Rooms to rent in the emblematic district of Al...,none,Almagro is a great place to plunge into the li...,...,f,f,strict_14_with_grace_period,f,f,19,3,16,0,0.10
848,1095098,https://www.airbnb.com/rooms/1095098,20200426042522,2020-04-26,BRING YOUR LUGGAGE (little flat),un departamentito dentro de un gran departamen...,Hola Viajeros! Este es un precioso departamen...,un departamentito dentro de un gran departamen...,none,Montserrat es uno de los barrios mas antiguos ...,...,f,f,strict_14_with_grace_period,f,f,2,1,1,0,0.27
987,1323164,https://www.airbnb.com/rooms/1323164,20200426042522,2020-04-27,Room in Buenos Aires. San cristobal.,"Single room, extremely bright, on a ninth floo...",NaN,"Single room, extremely bright, on a ninth floo...",none,town quiet.,...,f,f,strict_14_with_grace_period,f,f,2,0,2,0,0.10
1148,1757580,https://www.airbnb.com/rooms/1757580,20200426042522,2020-04-26,"Habitación en lugar antiguo, San Telmo","Una habitación c/entrepiso, 1 cama de una pza ...",Es un espacio tranquilo y confortable en el c...,"Una habitación c/entrepiso, 1 cama de una pza ...",none,Muy buena ubicación a 3 cuadras de la Av 9 de ...,...,f,f,strict_14_with_grace_period,f,f,2,0,2,0,0.43
1234,1922407,https://www.airbnb.com/rooms/1922407,20200426042522,2020-04-27,SHARED ROOM IN COLONIAL HOUSE NOT AVAILABLE,Super comfy shared room with with 3 beds. Fres...,Welcome to Mi Casa en BA: Mi Casa en BA is a r...,Super comfy shared room with with 3 beds. Fres...,none,Neighbourhood Highlights: Among the architectu...,...,f,f,strict_14_with_grace_period,t,t,7,1,5,1,0.05
1320,2092376,https://www.airbnb.com/rooms/2092376,20200426042522,2020-04-26,Single or double room,Habitación compartida o individual en piso com...,Linda habitación individual ideal para mujeres...,Habitación compartida o individual en piso com...,none,"Lindo barrio, cercano a la zona mas turística ...",...,f,f,flexible,f,f,12,4,8,0,0.17
1366,2175874,https://www.airbnb.com/rooms/2175874,20200426042522,2020-04-26,"Double bed, Recoleta, bath, balcon",Double Bedroom with balcon and bathroom for co...,This is an incredible double room very luminou...,Double Bedroom with balcon and bathroom for co...,none,"The neighborhood is amazing, is very safe and ...",...,f,f,moderate,f,f,3,0,3,0,1.05
13942,32463719,https://www.airbnb.com/rooms/32463719,20200426042522,2020-04-26,Habitación luminosa en departamento en San Telmo,NaN,NaN,NaN,none,NaN,...,f,f,flexible,f,f,1,0,1,0,NaN
18236,37961786,https://www.airbnb.com/rooms/37961786,20200426042522,2020-04-26,"Silencioso, luminoso y Confortable apartamento.","Amplio, luminoso, cómodo y cálido. Todo nuevo....","El departamento es grande, muy cómodo, equipad...","Amplio, luminoso, cómodo y cálido. Todo nuevo....",none,Supermercado cerca y muchas casas de comida ta...,...,t,f,flexible,f,f,1,1,0,0,NaN

In [63]:
# Se carga una segunda base de datos para hacer merge desde Python

calendardf2 = pd.read_csv('calendardf2.csv')

In [64]:
calendardf2.columns

Index(['listing_id', 'date', 'available', 'adjusted_price'], dtype='object')

In [65]:
combinadodf = pd.merge(calendardf2, listingsdf, on='listing_id')

In [68]:
combinadodf.columns

Index(['listing_id', 'date', 'available', 'adjusted_price', 'listing_url',
       'scrape_id', 'last_scraped', 'name', 'summary', 'space',
       ...
       'instant_bookable', 'is_business_travel_ready', 'cancellation_policy',
       'require_guest_profile_picture', 'require_guest_phone_verification',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object', length=109)

In [69]:
combinadodf['cancellation_policy']

0          strict_14_with_grace_period
1          strict_14_with_grace_period
2          strict_14_with_grace_period
3          strict_14_with_grace_period
4          strict_14_with_grace_period
                      ...
8661281                       moderate
8661282                       moderate
8661283                       moderate
8661284                       moderate
8661285                       moderate
Name: cancellation_policy, Length: 8661286, dtype: object

In [70]:
combinadodf = combinadodf[['listing_id', 'adjusted_price', 'available', 'neighbourhood', 'property_type', 'amenities', 'number_of_reviews', 'review_scores_rating', 'amenities', 'cancellation_policy']]

In [71]:
combinadodf

,listing_id,adjusted_price,available,neighbourhood,property_type,amenities,number_of_reviews,review_scores_rating,amenities,cancellation_policy
0,50778,2655,f,Recoleta,Condominium,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",96,88.0,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",strict_14_with_grace_period
1,50778,2655,t,Recoleta,Condominium,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",96,88.0,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",strict_14_with_grace_period
2,50778,2655,t,Recoleta,Condominium,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",96,88.0,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",strict_14_with_grace_period
3,50778,2655,t,Recoleta,Condominium,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",96,88.0,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",strict_14_with_grace_period
4,50778,2655,t,Recoleta,Condominium,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",96,88.0,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",strict_14_with_grace_period
...,...,...,...,...,...,...,...,...,...,...
8661281,43178560,3319,f,Villa Crespo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",0,NaN,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",moderate
8661282,43178560,3319,f,Villa Crespo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",0,NaN,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",moderate
8661283,43178560,3319,f,Villa Crespo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",0,NaN,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",moderate
8661284,43178560,3319,f,Villa Crespo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",0,NaN,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",moderate
8661285,43178560,3319,f,Villa Crespo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",0,NaN,"{TV,Wifi,""Air conditioning"",Pool,Gym,Heating,E...",moderate

In [26]:
# Se supone que la disponibilidad f (falso) es la cantidad de reservaciones, porque es falso que esté disponible por lo que fue reservado

# Se filtran las filas para conservar solamente las que den f en la columna available

filas_f = combinadodf[combinadodf['available'] == 'f']

# Se agrupa por 'listing_id' y se calcula la suma de 'adjusted_price' por cada 'listing__id' para jerarquizar por cantidad de ventas

precio_sum_listed = filas_f.groupby('listing_id')['adjusted_price'].sum()

# Se ordena en orden descendente

precio_sum_listed_sorted = precio_sum_listed.sort_values(ascending=False)

precio_sum_listed_sorted

listing_id
39489355    3634305
41475668    3634305
20491109    3634305
36470781    3634305
27051143    3409465
             ...
39063760        576
14817528        551
32951909        450
30336209        380
30335307        380
Name: adjusted_price, Length: 20000, dtype: int64

In [32]:
# Paso 1: Eliminar duplicados
combinadodf = combinadodf.drop_duplicates(subset='listing_id', keep='first')

# Paso 2: Unir DataFrames
combinadodf2 = combinadodf.merge(precio_sum_listed_sorted, on='listing_id', how='left', suffixes=('_original', '_sum'))

In [34]:
# Se vuelven a filtrar las filas para solo quedarnos con las 'f' en 'available'combinadodf2

combinadodf2 = combinadodf2[combinadodf2['available'] == 'f']

In [37]:
# Se ordena de mayor a menor en cuanto a ventas sumadas en la columna'adjusted_price_sum', resultado de la suma de todos los días en 'f' por propiedad o 'listing_id'

combinadodf2 = combinadodf2.sort_values(by='adjusted_price_sum', ascending=False)

In [38]:
combinadodf2

,listing_id,adjusted_price_original,available,neighbourhood,property_type,amenities,number_of_reviews,review_scores_rating,adjusted_price_sum
21755,41475668,9957,f,Palermo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Kitchen,Gym,H...",0,NaN,3634305.0
6805,20491109,9957,f,San Nicolás,Loft,"{TV,Wifi,Kitchen,""Pets allowed"",Elevator,Essen...",0,NaN,3634305.0
19607,39489355,9957,f,Palermo,Condominium,"{TV,Wifi,""Air conditioning"",Pool,""Free parking...",2,100.0,3634305.0
17113,36470781,9957,f,Recoleta,Condominium,"{TV,Wifi,Kitchen,Heating,Washer,Essentials,""Pr...",0,NaN,3634305.0
9708,27051143,9341,f,Palermo,Apartment,"{TV,""Cable TV"",Wifi,""Air conditioning"",Pool,Ki...",1,100.0,3409465.0
...,...,...,...,...,...,...,...,...,...
19137,39063760,576,f,Villa General Mitre,Apartment,"{TV,Wifi,""Air conditioning"",Kitchen}",0,NaN,576.0
5187,14817528,551,f,San Cristóbal,Apartment,"{TV,Wifi,Kitchen,""Pets live on this property"",...",5,100.0,551.0
14562,32951909,450,f,Floresta,Apartment,"{TV,Wifi,""Air conditioning"",Kitchen,""Smoking a...",0,NaN,450.0
12159,30335307,380,f,Constitución,House,"{TV,""Cable TV"",Wifi,Kitchen,Heating,""First aid...",0,NaN,380.0
12163,30336209,380,f,Constitución,House,"{TV,Wifi,Kitchen,Heating,""First aid kit"",""Fire...",0,NaN,380.0

In [39]:
# Se definen rangos de precios para entender cuáles son los 'listing_id' que mejor rendimiento tuvieron

rangos = [0, 1000000, 2000000, 2800000, 3647810, float('inf')]  # Puedes ajustar estos límites según tus necesidades


# Se definen las etiquetas para los rangos

etiquetas = ['1000000', '2000000', '2800000', '3647810', '3647810+']

# Se crea una nueva columna 'precio_rango' que asigna cada valor de adjusted_price a un rango

combinadodf2['precio_rango'] = pd.cut(combinadodf2['adjusted_price_sum'], bins=rangos, labels=etiquetas, right=False)

# Ahora, combinadodf contendrá la nueva columna 'precio_rango' con los rangos asignados

# Mostrar el DataFrame con las nuevas asignaciones

combinadodf2[['listing_id', 'adjusted_price_sum', 'precio_rango']]

       listing_id  adjusted_price_sum precio_rango
21755    41475668           3634305.0      3647810
6805     20491109           3634305.0      3647810
19607    39489355           3634305.0      3647810
17113    36470781           3634305.0      3647810
9708     27051143           3409465.0      3647810
...           ...                 ...          ...
19137    39063760               576.0      1000000
5187     14817528               551.0      1000000
14562    32951909               450.0      1000000
12159    30335307               380.0      1000000
12163    30336209               380.0      1000000

[16029 rows x 3 columns]

In [40]:
# Se cuenta la frecuencia de cada rango
conteo_por_rango = combinadodf2['precio_rango'].value_counts()

# Se calcula el porcentaje respecto al total que representa cada rango
porcentaje = (conteo_por_rango / len(combinadodf2)) * 100

# Se crea un DataFrame para mostrar los resultados
resultados = pd.DataFrame({'Frecuencia': conteo_por_rango, 'Porcentaje': porcentaje})

resultados

              Frecuencia  Porcentaje
precio_rango
1000000            14528   90.635723
2000000             1219    7.604966
2800000              252    1.572150
3647810               30    0.187161
3647810+               0    0.000000

In [ ]:
# Se establece que solamente 282 propiedades generan cantidades millonarias al año, por lo que esas son el objeto de estudio de este proyecto

In [42]:
# Filtrar las filas en el rango deseado

propiedades_top = combinadodf2[(combinadodf2['precio_rango'] == '2800000') | (combinadodf2['precio_rango'] == '3647810')]

propiedades_top

,listing_id,adjusted_price_original,available,neighbourhood,property_type,amenities,number_of_reviews,review_scores_rating,adjusted_price_sum,precio_rango
21755,41475668,9957,f,Palermo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Kitchen,Gym,H...",0,NaN,3634305.0,3647810
6805,20491109,9957,f,San Nicolás,Loft,"{TV,Wifi,Kitchen,""Pets allowed"",Elevator,Essen...",0,NaN,3634305.0,3647810
19607,39489355,9957,f,Palermo,Condominium,"{TV,Wifi,""Air conditioning"",Pool,""Free parking...",2,100.0,3634305.0,3647810
17113,36470781,9957,f,Recoleta,Condominium,"{TV,Wifi,Kitchen,Heating,Washer,Essentials,""Pr...",0,NaN,3634305.0,3647810
9708,27051143,9341,f,Palermo,Apartment,"{TV,""Cable TV"",Wifi,""Air conditioning"",Pool,Ki...",1,100.0,3409465.0,3647810
...,...,...,...,...,...,...,...,...,...,...
15867,34671738,7302,f,Recoleta,Apartment,"{TV,Wifi,Essentials,""Host greets you""}",0,NaN,2015352.0,2800000
4424,13634767,7302,f,Palermo,Apartment,"{TV,Internet,Wifi,""Air conditioning"",Pool,Kitc...",2,NaN,2015352.0,2800000
21732,41469827,7302,f,Monserrat,Apartment,"{TV,""Air conditioning"",Kitchen,Elevator,Heatin...",0,NaN,2015352.0,2800000
1883,3990394,7527,f,Palermo,Apartment,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",69,96.0,2006838.0,2800000
3897,11889458,5974,f,Balvanera,Apartment,"{TV,""Cable TV"",Internet,Wifi,""Air conditioning...",47,96.0,2001290.0,2800000

In [51]:
# Antes de utilizar los datos de las mejores propiedades, hacemos una base de datos dummy para graficarla en Power BI

combinadodf2_dummy = combinadodf2

In [52]:
# Se crean columnas dummy para los rangos de precios
dummy_columns_precio = pd.get_dummies(combinadodf2_dummy['precio_rango'])
dummy_columns_precio.columns = ['precio_' + col for col in dummy_columns_precio.columns]

# Crear columnas dummy para los rangos de porcentaje
dummy_columns_porcentaje = pd.get_dummies(combinadodf2_dummy['precio_rango'])
dummy_columns_porcentaje.columns = ['porcentaje_' + col for col in dummy_columns_porcentaje.columns]

# Concatenar las columnas dummy con el DataFrame original
combinadodf2_dummy = pd.concat([combinadodf2_dummy, dummy_columns_precio], axis=1)

# Mostrar el DataFrame resultante
combinadodf2_dummy

,listing_id,adjusted_price_original,available,neighbourhood,property_type,amenities,number_of_reviews,review_scores_rating,adjusted_price_sum,precio_rango,precio_1000000,precio_2000000,precio_2800000,precio_3647810,precio_3647810+
21755,41475668,9957,f,Palermo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Kitchen,Gym,H...",0,NaN,3634305.0,3647810,False,False,False,True,False
6805,20491109,9957,f,San Nicolás,Loft,"{TV,Wifi,Kitchen,""Pets allowed"",Elevator,Essen...",0,NaN,3634305.0,3647810,False,False,False,True,False
19607,39489355,9957,f,Palermo,Condominium,"{TV,Wifi,""Air conditioning"",Pool,""Free parking...",2,100.0,3634305.0,3647810,False,False,False,True,False
17113,36470781,9957,f,Recoleta,Condominium,"{TV,Wifi,Kitchen,Heating,Washer,Essentials,""Pr...",0,NaN,3634305.0,3647810,False,False,False,True,False
9708,27051143,9341,f,Palermo,Apartment,"{TV,""Cable TV"",Wifi,""Air conditioning"",Pool,Ki...",1,100.0,3409465.0,3647810,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19137,39063760,576,f,Villa General Mitre,Apartment,"{TV,Wifi,""Air conditioning"",Kitchen}",0,NaN,576.0,1000000,True,False,False,False,False
5187,14817528,551,f,San Cristóbal,Apartment,"{TV,Wifi,Kitchen,""Pets live on this property"",...",5,100.0,551.0,1000000,True,False,False,False,False
14562,32951909,450,f,Floresta,Apartment,"{TV,Wifi,""Air conditioning"",Kitchen,""Smoking a...",0,NaN,450.0,1000000,True,False,False,False,False
12159,30335307,380,f,Constitución,House,"{TV,""Cable TV"",Wifi,Kitchen,Heating,""First aid...",0,NaN,380.0,1000000,True,False,False,False,False
12163,30336209,380,f,Constitución,House,"{TV,Wifi,Kitchen,Heating,""First aid kit"",""Fire...",0,NaN,380.0,1000000,True,False,False,False,False

In [54]:
# Reemplazar True por 1 y False por 0
combinadodf2_dummy[['precio_1000000', 'precio_2000000', 'precio_2800000', 'precio_3647810', 'precio_3647810+']] = combinadodf2_dummy[['precio_1000000', 'precio_2000000', 'precio_2800000', 'precio_3647810', 'precio_3647810+']].replace({True: 1, False: 0})
combinadodf2_dummy

,listing_id,adjusted_price_original,available,neighbourhood,property_type,amenities,number_of_reviews,review_scores_rating,adjusted_price_sum,precio_rango,precio_1000000,precio_2000000,precio_2800000,precio_3647810,precio_3647810+
21755,41475668,9957,f,Palermo,Apartment,"{TV,Wifi,""Air conditioning"",Pool,Kitchen,Gym,H...",0,NaN,3634305.0,3647810,0,0,0,1,0
6805,20491109,9957,f,San Nicolás,Loft,"{TV,Wifi,Kitchen,""Pets allowed"",Elevator,Essen...",0,NaN,3634305.0,3647810,0,0,0,1,0
19607,39489355,9957,f,Palermo,Condominium,"{TV,Wifi,""Air conditioning"",Pool,""Free parking...",2,100.0,3634305.0,3647810,0,0,0,1,0
17113,36470781,9957,f,Recoleta,Condominium,"{TV,Wifi,Kitchen,Heating,Washer,Essentials,""Pr...",0,NaN,3634305.0,3647810,0,0,0,1,0
9708,27051143,9341,f,Palermo,Apartment,"{TV,""Cable TV"",Wifi,""Air conditioning"",Pool,Ki...",1,100.0,3409465.0,3647810,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19137,39063760,576,f,Villa General Mitre,Apartment,"{TV,Wifi,""Air conditioning"",Kitchen}",0,NaN,576.0,1000000,1,0,0,0,0
5187,14817528,551,f,San Cristóbal,Apartment,"{TV,Wifi,Kitchen,""Pets live on this property"",...",5,100.0,551.0,1000000,1,0,0,0,0
14562,32951909,450,f,Floresta,Apartment,"{TV,Wifi,""Air conditioning"",Kitchen,""Smoking a...",0,NaN,450.0,1000000,1,0,0,0,0
12159,30335307,380,f,Constitución,House,"{TV,""Cable TV"",Wifi,Kitchen,Heating,""First aid...",0,NaN,380.0,1000000,1,0,0,0,0
12163,30336209,380,f,Constitución,House,"{TV,Wifi,Kitchen,Heating,""First aid kit"",""Fire...",0,NaN,380.0,1000000,1,0,0,0,0

In [55]:
combinadodf2_dummy = combinadodf2_dummy[['listing_id', 'adjusted_price_original', 'available', 'adjusted_price_sum', 'precio_rango', 'precio_1000000', 'precio_2000000', 'precio_2800000', 'precio_3647810']]

In [56]:
# Se extrae para tabla de porcentajes

combinadodf2_dummy.to_csv('combinadodf2_dummy.csv', index=False)  # Setear index=False para no anexar la columna de índice numérico

In [57]:
# Se extrae para presentar tablas

propiedades_top.to_csv('propiedades_top.csv', index=False)  # Setear index=False para no anexar la columna de índice numérico